{
  "contest": 386,
  "handle": "mt030d",
  "risk": "3",
  "title": "`_transferOutAndCallV5` does not revert when the swap in aggregator fails, leading to loss of recipient's funds",
  "issueId": 92,
  "issueUrl": "https://github.com/code-423n4/2024-06-thorchain-findings/issues/92",
  "originalIssueId": 9,
  "originalIssueUrl": "https://github.com/code-423n4/2024-06-thorchain-validation/issues/9"
}